version: "3.7"

services:
  py-backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 5000:5000
    dns:
      - 8.8.8.8
    volumes:
      - ./backend:/app
    environment:
      - TEST_MONGO_USER
      - TEST_MONGO_PASS
      - TEST_MONGO_HOST
      - TEST_MONGO_DB
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME: TEST_MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD: TEST_MONGO_PASS
      - MONGO_INITDB_DATABASE: TEST_MONGO_DB
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 10s
      timeout: 5s
      retries: 5
