version: "3.7"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    dns:
      - 8.8.8.8
    volumes:
      - ./backend:/app
    environment:
      - TEST_MONGODB_URL
      - FIREBASE_PROJECT_ID
      - FIREBASE_PRIVATE_KEY_ID
      - FIREBASE_PRIVATE_KEY
      - FIREBASE_CLIENT_EMAIL
      - FIREBASE_CLIENT_ID
      - FIREBASE_AUTH_URI
      - FIREBASE_TOKEN_URI
      - FIREBASE_AUTH_PROVIDER_X509_CERT_URL
      - FIREBASE_CLIENT_X509_CERT_URL
      - FIREBASE_WEB_API_KEY
      - FIREBASE_REFRESH_TOKEN_URL
      - FIREBASE_SIGN_IN_URL
      - MAIL_SERVER
      - MAIL_PORT
      - MAIL_USE_SSL
      - MAIL_USERNAME
      - MAIL_PASSWORD
