import datetime
import os
import random
import sys

from app import create_app
from app.models.course import ClassType, Course, CourseType, Section, Weekday
from app.models.user import Schedule, ScheduleCourses, User


def add_courses():
    print("Seeding courses...")
    courses = [
        Course(
            name="Fundamental Engineering Math 1",
            department="SYDE",
            code="111",
            description="Functions: trigonometric, exponential, log, inverse functions. Differential calculus: limits, continuity, derivatives, differentials, applications. Sequences and series: convergence, power series, Taylor expansions. Simple numerical methods. [Offered: F]",
            ceab_math=42.0,
            course_type=CourseType.REQUIRED,
            sections=[
                Section(
                    day=[Weekday.M, Weekday.W],
                    term_code="1229",
                    instructor="Mr. Peanutbutter",
                    start_time=510,
                    end_time=590,
                    class_number=4877,
                    location="E5 6008",
                    type=ClassType.LEC,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=102,
                    capacity=102,
                ),
                Section(
                    day=[Weekday.T, Weekday.TH],
                    term_code="1229",
                    instructor="Princess Carolyn",
                    start_time=510,
                    end_time=590,
                    class_number=4878,
                    location="E5 6008",
                    type=ClassType.LEC,
                    number="002",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=102,
                    capacity=102,
                ),
                Section(
                    day=[Weekday.F],
                    term_code="1229",
                    instructor="Princess Carolyn",
                    start_time=510,
                    end_time=560,
                    class_number=4879,
                    location="E5 6008",
                    type=ClassType.TUT,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=102,
                    capacity=102,
                ),
            ],
        ),
        Course(
            name="Fundamental Engineering Math 2",
            department="SYDE",
            code="112",
            description="Integration: Indefinite and definite integral; techniques of integration; improper integrals, numerical methods, applications. Vector differential calculus: Partial, total, and directional derivative; Gradient divergence and curl; Jacobian. Applications. [Offered: W, S]",
            ceab_math=42.0,
            course_type=CourseType.REQUIRED,
            sections=[
                Section(
                    day=[Weekday.M, Weekday.W],
                    term_code="1229",
                    instructor="Todd Chavez",
                    start_time=600,
                    end_time=680,
                    class_number=4977,
                    location="E5 6008",
                    type=ClassType.LEC,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=102,
                    capacity=102,
                ),
                Section(
                    day=[Weekday.T, Weekday.TH],
                    term_code="1229",
                    instructor="Todd Chavez",
                    start_time=600,
                    end_time=680,
                    class_number=4978,
                    location="E5 6008",
                    type=ClassType.LEC,
                    number="002",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=102,
                    capacity=102,
                ),
                Section(
                    day=[Weekday.F],
                    term_code="1229",
                    instructor="Todd Chavez",
                    start_time=600,
                    end_time=650,
                    class_number=4979,
                    location="E5 6008",
                    type=ClassType.TUT,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=102,
                    capacity=102,
                ),
            ],
        ),
        Course(
            name="Numerical and Applied Calculus",
            department="SYDE",
            code="114",
            description="Matrices and linear systems: determinants, eigenvalues and eigenvectors, LU decomposition, conditioning, numerical methods. First order ordinary differential equations: analytical techniques, applications, elementary numerical methods, convergence. [Offered: W, S]",
            ceab_math=36.0,
            course_type=CourseType.REQUIRED,
            prerequisites=["SYDE 113"],
            tags=["matrices", "linear algebra"],
            sections=[
                Section(
                    day=[Weekday.T, Weekday.F],
                    term_code="1229",
                    instructor="Diane Nguyen",
                    start_time=900,
                    end_time=980,
                    class_number=4077,
                    location="E5 6008",
                    type=ClassType.LEC,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=102,
                    capacity=102,
                ),
                Section(
                    day=[Weekday.M],
                    term_code="1229",
                    instructor="Diane Nguyen",
                    start_time=1140,
                    end_time=1190,
                    class_number=4979,
                    location="E5 6008",
                    type=ClassType.TUT,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=102,
                    capacity=102,
                ),
            ],
        ),
        Course(
            name="Digital Computation",
            department="SYDE",
            code="121",
            description="Computer systems, problem solving, data and programs, structured programming, arrays, matrices and pointers, correct and efficient algorithms, data structures. [Offered: F]",
            ceab_eng_sci=27.0,
            ceab_eng_design=27.0,
            course_type=CourseType.REQUIRED,
            prerequisites=["SYDE 101L"],
            tags=["computer", "programming"],
            sections=[
                Section(
                    day=[Weekday.M, Weekday.F],
                    term_code="1229",
                    instructor="Meow Meow Fuzzyface",
                    start_time=810,
                    end_time=900,
                    class_number=4021,
                    location="E5 6008",
                    type=ClassType.LEC,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=102,
                    capacity=102,
                ),
                Section(
                    day=[Weekday.TH],
                    term_code="1229",
                    instructor="Meow Meow Fuzzyface",
                    start_time=1140,
                    end_time=1190,
                    class_number=4022,
                    location="E5 6008",
                    type=ClassType.TUT,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=102,
                    capacity=102,
                ),
                Section(
                    day=[Weekday.W],
                    term_code="1229",
                    instructor="Meow Meow Fuzzyface",
                    start_time=720,
                    end_time=830,
                    class_number=4023,
                    location="E5 6008",
                    type=ClassType.LAB,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=102,
                    capacity=102,
                ),
            ],
        ),
        Course(
            name="Engineering Design",
            department="SYDE",
            code="361",
            description="The methodology of design, situation of concern; needs analysis and problem definition, engineering analysis and generation of alternative solutions, design prototyping, and design documentation. The lecture material is supplemented by a term-long design project done in small groups that develops hands-on experience with electromechanical prototyping. [Offered: S]",
            ceab_eng_sci=14.3,
            ceab_eng_design=42.8,
            course_type=CourseType.REQUIRED,
            sections=[
                Section(
                    day=[Weekday.M, Weekday.F],
                    term_code="1229",
                    instructor="Ralph Stilton",
                    start_time=810,
                    end_time=900,
                    class_number=4123,
                    location="E5 6008",
                    type=ClassType.LEC,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=102,
                    capacity=102,
                ),
                Section(
                    day=[Weekday.TH],
                    term_code="1229",
                    instructor="Ralph Stilton",
                    start_time=1140,
                    end_time=1190,
                    class_number=4124,
                    location="E5 6008",
                    type=ClassType.TUT,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=102,
                    capacity=102,
                ),
                Section(
                    day=[Weekday.W],
                    term_code="1229",
                    instructor="Neal McBeal",
                    start_time=720,
                    end_time=830,
                    class_number=4125,
                    location="E5 6008",
                    type=ClassType.LAB,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=102,
                    capacity=102,
                ),
            ],
        ),
        Course(
            name="Thermodynamics",
            department="SYDE",
            code="381",
            description="An introductory course in engineering thermodynamics structured for students in Systems Design. Classical thermodynamics is presented as the systematic study of energy; its use, degradation, and waste. Introduction to heat transfer by conduction, convection, and radiation. Applications focus on problems of energy and environment. The concepts of statistical thermodynamics are introduced. [Offered: S]",
            ceab_sci=18.9,
            ceab_eng_sci=23.1,
            course_type=CourseType.REQUIRED,
            prerequisites=["SYDE 383"],
            tags=["thermodynamics", "physics"],
            sections=[
                Section(
                    day=[Weekday.T, Weekday.F],
                    term_code="1229",
                    instructor="Dean Squooshyface",
                    start_time=900,
                    end_time=980,
                    class_number=4192,
                    location="E5 6008",
                    type=ClassType.LEC,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=90,
                    capacity=100,
                ),
                Section(
                    day=[Weekday.M],
                    term_code="1229",
                    instructor="Dean Squooshyface",
                    start_time=1140,
                    end_time=1190,
                    class_number=4193,
                    location="E5 6008",
                    type=ClassType.TUT,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=90,
                    capacity=100,
                ),
            ],
        ),
        Course(
            name="Algorithm Design and Analysis",
            department="ECE",
            code="406",
            description="Design and analysis of efficient, correct algorithms. Advanced data structures, divide-and-conquer algorithms, recurrences, greedy algorithms, dynamic programming, graph algorithms, search and backtrack, inherently hard and unsolvable problems, approximation and randomized algorithms, and amortized analysis. [Offered: W]",
            ceab_eng_sci=34.17,
            ceab_eng_design=16.83,
            course_type=CourseType.TE,
            sections=[
                Section(
                    day=[Weekday.T, Weekday.F],
                    term_code="1229",
                    instructor="Charley Witherspoon",
                    start_time=900,
                    end_time=980,
                    class_number=4910,
                    location="E7 5353",
                    type=ClassType.LEC,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=120,
                    capacity=135,
                ),
                Section(
                    day=[Weekday.M],
                    term_code="1229",
                    instructor="Charley Witherspoon",
                    start_time=1140,
                    end_time=1190,
                    class_number=4911,
                    location="E7 5353",
                    type=ClassType.TUT,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=120,
                    capacity=135,
                ),
            ],
        ),
        Course(
            name="Advanced Topics in Networking",
            department="ECE",
            code="416",
            description="This course introduces advanced topics in networking with a focus on applications and wireless technologies. Topics include: Cellular networks (2G, 3G, 4G and beyond), applications (Domain Name System [DNS], Simple Mail Transfer Protocol[SMTP], Post Office Protocol [POP], Internet Message Access Protocol [ IMAP], Hypertext Transfer Protocol [HTTP]) and socket programming, Content-centric networks (content delivery networks, peer-to-peer protocols, data centers, etc.), protocols for multimedia applications (Session Initiation Protocol [SIP], Real-time Transport Protocol [RTP], RTP Control Protocol [RTCP]), emerging technologies (Internet of Things, sensors, software defined networks), policy issues (network neutrality, who controls the Internet?). [Offered W]",
            ceab_math=12.75,
            ceab_eng_sci=15.3,
            ceab_eng_design=22.95,
            course_type=CourseType.TE,
            prerequisites=["ECE 358"],
            antirequisites=["ECE 461"],
            tags=["network", "internet"],
            sections=[
                Section(
                    day=[Weekday.T, Weekday.F],
                    term_code="1229",
                    instructor="Crackerjack Sugarman",
                    start_time=900,
                    end_time=980,
                    class_number=4419,
                    location="E7 5533",
                    type=ClassType.LEC,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=90,
                    capacity=100,
                ),
                Section(
                    day=[Weekday.M],
                    term_code="1229",
                    instructor="Crackerjack Sugarman",
                    start_time=1140,
                    end_time=1190,
                    class_number=4420,
                    location="E7 5533",
                    type=ClassType.TUT,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=90,
                    capacity=100,
                ),
            ],
        ),
        Course(
            name="Introduction to Machine Learning",
            department="MSCI",
            code="546",
            description="This course covers algorithmic and statistical foundations of data mining: extracting previously unknown and useful information from data. Topics include exploratory data analysis, data cleaning, data transformations, association rule mining, and both supervised and unsupervised learning. Methods typically covered include, but are not limited to: the Apriori algorithm, Bayesian inference, decision trees, linear and logistic regression, nearest-neighbor classification, and k-means clustering. [Offered: W]",
            ceab_eng_sci=25.2,
            ceab_eng_design=16.8,
            course_type=CourseType.TE,
            antirequisites=["SYDE 599"],
            tags=["algorithm", "statistics"],
            sections=[
                Section(
                    day=[Weekday.T, Weekday.F],
                    term_code="1229",
                    instructor="Rutabaga Rabitowitz",
                    start_time=900,
                    end_time=980,
                    class_number=4900,
                    location="E7 4757",
                    type=ClassType.LEC,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=120,
                    capacity=120,
                ),
                Section(
                    day=[Weekday.M],
                    term_code="1229",
                    instructor="Rutabaga Rabitowitz",
                    start_time=1140,
                    end_time=1190,
                    class_number=4901,
                    location="E7 4757",
                    type=ClassType.TUT,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=120,
                    capacity=120,
                ),
            ],
        ),
        Course(
            name="First-Year Japanese 1",
            department="JAPAN",
            code="101R",
            description="An introductory course for students who have little or no knowledge of Japanese to develop basic listening, speaking, reading, and writing skills. Practical oral and written exercises incorporating the Hiragana Writing System provide a firm grammatical foundation for further study.",
            cse_weight=36.0,
            course_type=CourseType.LIST_D,
            sections=[
                Section(
                    day=[Weekday.M],
                    term_code="1229",
                    instructor="Judah Mannowdog",
                    start_time=600,
                    end_time=680,
                    class_number=1010,
                    location="REN 1201",
                    type=ClassType.LEC,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=45,
                    capacity=45,
                ),
                Section(
                    day=[Weekday.M],
                    term_code="1229",
                    instructor="Judah Mannowdog",
                    start_time=690,
                    end_time=780,
                    class_number=1011,
                    location="REN 1201",
                    type=ClassType.LEC,
                    number="002",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=45,
                    capacity=45,
                ),
                Section(
                    day=[Weekday.T],
                    term_code="1229",
                    instructor="Judah Mannowdog",
                    start_time=600,
                    end_time=680,
                    class_number=1012,
                    location="REN 210B",
                    type=ClassType.TUT,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=30,
                    capacity=30,
                ),
                Section(
                    day=[Weekday.T],
                    term_code="1229",
                    instructor="Judah Mannowdog",
                    start_time=690,
                    end_time=780,
                    class_number=1013,
                    location="REN 210B",
                    type=ClassType.TUT,
                    number="002",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=28,
                    capacity=30,
                ),
                Section(
                    day=[Weekday.T],
                    term_code="1229",
                    instructor="Judah Mannowdog",
                    start_time=790,
                    end_time=880,
                    class_number=1014,
                    location="REN 210B",
                    type=ClassType.TUT,
                    number="003",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=15,
                    capacity=30,
                ),
            ],
        ),
        Course(
            name="First-Year Japanese 2",
            department="JAPAN",
            code="102R",
            description="Listening, speaking, reading, and writing skills acquired in JAPAN 101R are further developed. Practical oral and written exercises incorporating the Katakana Writing System are used to develop a more solid grammatical base.",
            cse_weight=36.0,
            course_type=CourseType.LIST_D,
            prerequisites=["JAPAN 101R"],
            tags=["japan", "language"],
            sections=[
                Section(
                    day=[Weekday.M],
                    term_code="1229",
                    instructor="Judah Mannowdog",
                    start_time=600,
                    end_time=680,
                    class_number=1110,
                    location="REN 1202",
                    type=ClassType.LEC,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=42,
                    capacity=45,
                ),
                Section(
                    day=[Weekday.M],
                    term_code="1229",
                    instructor="Judah Mannowdog",
                    start_time=690,
                    end_time=780,
                    class_number=1111,
                    location="REN 1202",
                    type=ClassType.LEC,
                    number="002",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=45,
                    capacity=45,
                ),
                Section(
                    day=[Weekday.T],
                    term_code="1229",
                    instructor="Judah Mannowdog",
                    start_time=600,
                    end_time=680,
                    class_number=1112,
                    location="REN 210A",
                    type=ClassType.TUT,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=30,
                    capacity=32,
                ),
                Section(
                    day=[Weekday.T],
                    term_code="1229",
                    instructor="Judah Mannowdog",
                    start_time=690,
                    end_time=780,
                    class_number=1113,
                    location="REN 210A",
                    type=ClassType.TUT,
                    number="002",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=30,
                    capacity=31,
                ),
                Section(
                    day=[Weekday.T],
                    term_code="1229",
                    instructor="Judah Mannowdog",
                    start_time=790,
                    end_time=880,
                    class_number=1114,
                    location="REN 210A",
                    type=ClassType.TUT,
                    number="003",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=30,
                    capacity=29,
                ),
            ],
        ),
        Course(
            name="Popular Music and Culture",
            department="MUSIC",
            code="140",
            description="An examination of the styles, forms, and development of 20th century popular music. The social, commercial, and technological aspects of popular music are considered.",
            cse_weight=36.0,
            course_type=CourseType.LIST_C,
            antirequisites=["MUSIC 140"],
            tags=["music", "culture"],
            sections=[
                Section(
                    day=[Weekday.M],
                    term_code="1229",
                    instructor="Virgil Van Cleef",
                    start_time=1140,
                    end_time=1250,
                    class_number=1509,
                    location="EV3 3201",
                    type=ClassType.LEC,
                    number="001",
                    start_date=datetime.datetime(2023, 9, 7),
                    end_date=datetime.datetime(2023, 12, 17),
                    enrolled_number=200,
                    capacity=200,
                )
            ],
        ),
    ]
    for course in courses:
        course.save()


def get_random_course_ids(courses, num_courses=3):
    course_oids = set()
    for _ in range(num_courses):
        r_idx = random.randrange(0, len(courses))
        course_oids.add(courses[r_idx].to_serializable_dict()["id"])
    return list(course_oids)


def get_schedule_courses(courses, num_courses=3):
    saved_courses = get_random_course_ids(courses, num_courses)
    course_colors = [
        "#ff6961",
        "#ffb480",
        "#e5d54a",
        "#42d6a4",
        "#08cad1",
        "#59adf6",
        "#9d94ff",
        "#c780e8",
    ]
    schedule_courses = []
    for course_oid in saved_courses:
        schedule_courses.append(
            ScheduleCourses(
                course_id=course_oid,
                section_id=Course.objects(_id=course_oid).first().sections[0]._id,
                color=random.choice(course_colors),
            )
        )
    return schedule_courses


def add_users():
    print("Seeding users...")
    courses = Course.objects.all()
    users = [
        User(
            name="Cloud Bread",
            email="breadfydp+cloud@gmail.com",
            grad_year="2023",
            program="SYDE",
            auth_id=os.getenv("TEST_USER_CLOUD_AUTH_ID"),
            saved_courses=get_random_course_ids(courses, 1),
            schedule=Schedule(term="1229", courses=get_schedule_courses(courses, 1)),
        ),
        User(
            name="Hokkaido Milk Bread",
            email="breadfydp+hokkaidomilk@gmail.com ",
            grad_year="2023",
            program="BME",
            auth_id=os.getenv("TEST_USER_HOKKAIDO_AUTH_ID"),
            saved_courses=get_random_course_ids(courses, 3),
            schedule=Schedule(term="1229", courses=get_schedule_courses(courses, 3)),
        ),
        User(
            name="Melon Bread",
            email="breadfydp+melon@gmail.com ",
            grad_year="2025",
            program="SYDE",
            auth_id=os.getenv("TEST_USER_MELON_AUTH_ID"),
            saved_courses=get_random_course_ids(courses, 7),
            schedule=Schedule(term="1229", courses=get_schedule_courses(courses, 7)),
        ),
        User(
            name="Egg Bread",
            email="breadfydp+egg@gmail.com ",
            grad_year="2025",
            program="SYDE",
            auth_id=os.getenv("TEST_USER_EGG_AUTH_ID"),
            saved_courses=get_random_course_ids(courses, 4),
            schedule=Schedule(term="1229", courses=get_schedule_courses(courses, 4)),
        ),
        User(
            name="Brioche Bread",
            email="breadfydp+brioche@gmail.com ",
            grad_year="2027",
            program="BME",
            auth_id=os.getenv("TEST_USER_BRIOCHE_AUTH_ID"),
            saved_courses=get_random_course_ids(courses, 2),
            schedule=Schedule(term="1229", courses=get_schedule_courses(courses, 2)),
        ),
    ]
    for user in users:
        user.save()


def clear_database():
    print("Clearing database...")
    User.objects().delete()
    Course.objects().delete()
    print("Database cleared 🗑")


def seed_database():
    print("Seeding database...")
    add_courses()
    add_users()
    print("Database seeded 🌱")


if __name__ == "__main__":
    app = create_app("development")
    if "clear" in sys.argv:
        clear_database()
    else:
        seed_database()
