name: Docker build backend

on:
  # Triggers the workflow on push or pull request events for the main branch
  push:
    # paths:
    #   - "backend/**"
  #   branches:
  #     - main
  # pull_request:
  #   paths:
  #     - "backend/**"
  #   branches:
  #     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TEST_MONGO_USER: ${{ secrets.TEST_MONGO_USER }}
      TEST_MONGO_PASS: ${{ secrets.TEST_MONGO_PASS }}
      TEST_MONGO_DB: ${{ secrets.TEST_MONGO_DB }}
      TEST_MONGODB_URL: ${{ format('mongodb://{0}:{1}@{2}:27017/{3}', secrets.TEST_MONGO_USER, secrets.TEST_MONGO_PASS, secrets.TEST_MONGO_HOST, secrets.TEST_MONGO_DB) }}

      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
      FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
      FIREBASE_AUTH_URI: ${{ secrets.FIREBASE_AUTH_URI }}
      FIREBASE_TOKEN_URI: ${{ secrets.FIREBASE_TOKEN_URI }}
      FIREBASE_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}
      FIREBASE_CLIENT_X509_CERT_URL: ${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}
      FIREBASE_WEB_API_KEY: ${{ secrets.FIREBASE_WEB_API_KEY }}
      FIREBASE_REFRESH_TOKEN_URL: ${{ secrets.FIREBASE_REFRESH_TOKEN_URL }}
      FIREBASE_SIGN_IN_URL: ${{ secrets.FIREBASE_SIGN_IN_URL }}
    steps:
      - uses: actions/checkout@v3

      # building the docker containers
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.ci.yml up -d

      # check running containers
      - name: Check running containers
        run: docker ps -a

      - name: Run backend unit tests
        run: docker exec backend /bin/bash -c "python -m pytest"
