name: Docker build backend

on:
  # Triggers the workflow on push or pull request events for the main branch
  push:
    paths:
      - "backend/**"
    branches:
      - main
  pull_request:
    paths:
      - "backend/**"
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      MONGODB_URL: ${{ secrets.MONGODB_URL_DEV }}

    steps:
      - uses: actions/checkout@v2

      # building the docker containers
      - name: Build the docker-compose stack
        run: docker-compose up py-backend -d

      # check running containers
      - name: Check running containers
        run: docker ps -a
