name: Lint codebase

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"
      - "data/**"
  pull_request:
    branches:
      - main

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Filter changed files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - "frontend/**"
            python-backend:
              - "backend/**"
            data:
              - "data/**"
      - name: Set up Node.js
        if: steps.changes.outputs.frontend == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: "14.19"
          cache: "yarn"
          cache-dependency-path: |
            frontend/yarn.lock
      - name: Install Node.js dependencies
        if: steps.changes.outputs.frontend == 'true'
        run: yarn --cwd ./frontend --prefer-offline

      - name: Lint frontend
        if: steps.changes.outputs.frontend == 'true'
        working-directory: ./frontend
        run: yarn lint

      - name: Lint Python backend
        if: steps.changes.outputs.python-backend == 'true'
        working-directory: ./backend
        run: pip install black isort && python -m black --check . && isort --profile black . -c

      - name: Lint data code
        if: steps.changes.outputs.data == 'true'
        working-directory: ./data
        run: pip install black isort && python -m black --check . && isort --profile black . -c
